sudo: required

services:
  - docker

env:
  global:
    - VERSION=latest
    - GITHUB_REPO=crazy-max/docker-svn2git-mirror
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=svn2git-mirror
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=svn2git-mirror
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/svn2git-mirror/KkTg5nSGpEj8NmQBMmAVJ3QSzko=
    - secure: DGOayQVTsgX8mO2vT0SdMp53uNJJ/znyVx90LmJZDRTxdWOZCsQfUTrkuM+gsBO4RV23ThPloc2kIC+s+NW+Z4vfZVK6XE2ZLRrelhbrz8AzUiV8Psh3Mc6vHKixl3FAYwTnQPxt7LcjAu+6z0+Hg073GEHFK1Mb8jtcgn40Bw6x2jnRnwrthwVauCIX9F1oCVahxyMC7lfifj0jxmnzQk8JBTYdTkvov7ok4GY9dAtx8RUKeWo5EBwvfThZZMPmxLfbz1VxySqGN2qnBXfKMphWtKeBRCBX4lcHMks9iFEQcQxriswV+rJg/f7mN17s5zxqbbVs96JKi5aHZa21hmWr9B5yODpTyJY6LNRxUDpXRAaS7OnLC79pPctIc8X5tMxUBnfqJkl+avrGe7AP/btJdAQswkqoX7NL+UzyAijvQ9do4MPUffEi7bB9vjHAyfhORmXn6z4jVKBUM+CLRNTou4S5uh9aTCMn4DjxXQx6NYQzaCxC1UqTvWmezi+udOnZ8hmlRGhcYl7Iv76o/glM+aXLSxJuWryrprLU/IeAlAufcP5cBdFxHqtmrWMAMsraamuVXUFtszCfsSVJ+zikICLt/+6Xlx+ISTEC6LyJMKv0UnDKZkcVk2d8WJ1u4Pklo+XQ/eZOV7eWEeCPYW/nvcy7qdQTuv/WEzDcaho= # DOCKER_PASSWORD
    - secure: kE5t+ogWBQ2Iiw7ZTRnamCgWrYa1gaDmdYAM75Fi75MdlFeUoWGuDYN1YirAsLwUFtl3B4Cjzq526YyG6sUyPXuI/6mWbRrUc0JsmEbEtQL6ESKywUXRfv7v+KiiH8msFpdsedzUHnZy0dulVw7ajFG6xO6YLzWksJJryQZ46FznqFuFO6mQUi3+hNn5LzDlfscEiOYpJv7lh7Szw2ylMy25AUfkaIpNA94cThSKh5CHmxco74RxwoTNmFPcrPKea+AqTuUUC+UeYKazVu6Ctheays9CBS4s2uPTr4WKmFeBeLxn23K9O6gYGt4xaQBboJlsvDn1Vt15+dW1PwvxL7FCE6sVp3g7M73MAtpbIruSoP2Dw6xCAT6ZI30nHfgjIQ3UHnMOTMPNGnCPm3hEFJKH7nZfTX2S0IGxx0RA+93t2+lMrLtmkZubnJkiLnV6zZg/A0SfSZuYKy3jXVz3bp/4d6s0fR1Beveafc6XBFAgfIjNoAgsAG99sMo2mrj/WZQbdUUek4+bulMqVCzI8CWFjsL93DH+Ij9antNu2v9sHEUxgGwb31l5Lr7W4OGBXEiiSfzieQjVh0c5s9W+qy473+fN96wnGNjV6QaN0oFqbwgVY4j4ry91P3Ymr+bbolnUABpLQsfGikmhUi2kqlTP0vIbNXg6gBjpPUPWmO0= # QUAY_PASSWORD
    - secure: cdeXcQi3Zge+9DjqLeloDRZRi28aPJoWnGgtbIKwmyFdUQ8l8rTgBn3MmoN98gvNNKYgR3daqda1a20PwR2O7kLywSeiPKgzhITr6Qkh3phPNA3ygTdQ7QSIudeyy9N4UuqLn+dRfQJIkffrzWUaNOeKIKdTvj7kQOrLh1D2B5V7/yYBGo5oXZZUj7Wi/SQiE+hMN16q0CCEdenAryUF8Zoua/3X4/pLGNLaWCtz4v5/eNcV9ewcLsBWB0LqAvU0Sb/k3D84y5+OXWt9xeo+77Wud3wdZopmh/O11xpdcG5v3EcCzUajqCJoRexirR1rZk9InGMq2e8vMGIRsBNXFVioZCjAxpw7Ryd6VvMg1M3TcaLveF3fXL38Y0vzNS1gI38TSrm8sm3LKNqv3AN5tWNohVlsMX95uI3VOfHR0NFb19yg6JZzfzVm5QYkx5uqWBNM3Y08HFxfHeN3nd+Epco4y8elPyCPhnfPphGiL/FV6z3H/yZLH4gREQBHoc1akhyKYG8g9J08Psadnmv276pJXo8IEOgZcNUsgPDiCbPG9LEw8/LaySVT3EGtFKYa93LjUk4cs5HhSs7tz2wQuBAOvPLgdXwknW5LnqxIENsRh+ErEDzksizD2oy//H2ZbAnNlmT8TRxBgrMflyi78if7wDN9bhxALBIaCbJgA0A= # GITHUB_TOKEN

before_install:
  - sudo apt-get update
  - docker --version
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DOCKER_TAG=$VERSION"

install:
  - |
    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=${TRAVIS_COMMIT::8} \
    --build-arg VERSION=${VERSION} \
    -t docker_build .

before_script:
  - |
    docker run -d \
    -v $(pwd)/.res/config.json:/etc/svn2git-mirror/config.json \
    --name $DOCKER_REPONAME docker_build
  - sleep 10
  - docker logs $DOCKER_REPONAME

script:
  - docker ps | grep $DOCKER_REPONAME
  - docker exec -it $DOCKER_REPONAME git_pubkey ant-contrib
  - docker exec -it $DOCKER_REPONAME svn_authors ant-contrib

after_success:
  - |
    test $TRAVIS_PULL_REQUEST = false \
    && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin \
    && docker tag docker_build $DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push $DOCKER_USERNAME/$DOCKER_REPONAME \
    && echo "$QUAY_PASSWORD" | docker login quay.io --username "$QUAY_USERNAME" --password-stdin \
    && docker tag docker_build quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push quay.io/$QUAY_USERNAME/$QUAY_REPONAME \
    && curl -X POST $MICROBADGER_HOOK

branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    secure: WoD+LLWxUQDftFG3SsMgwIt1yih3vD4Su9Gaa7rYnhXJY1wWmoHA6/NWXt4iWsvQvJf7A7+Ul13C3M5l5fdby7AvcrGLcfLa222nu85wK7unJ+MolsTUro7kjvYw2RbVcpOTxvBuT3myVQ/edeTEG2A+UkJyenMMJHbQwC2vadg1SSEzsF0oSq/tyWm5xcdHScvaKfGsKNRPCOS7GB/YH9+tOV5TQTW4nBL2XWKHUob4CTkS3peQjuvKub9Ioh1+jUerx/oFXUzAyLroKHqIW7+42sr6UkabvCKjS6XL97Nd8Uo1luTRoDmewfjHKlEX1GKDksIgQ1biNCmM1XVYc0aQLz+KMiHEnP2yUQkDZ0qUJ3PAWgLwZx6ss3xHU6cL6SBNGgIcHbmFQsrMOGQqb9HfREY/8Fv8PLu+fSx/vHyb955HkFBEaYJ1Kdlg2v+Drh18CejQTdlgepWKZyTLNImfuJg6DJ3uOzT+3CgmKoTs9Elr1Fw1o5zs1zmxrA6EIT9yFpIifE/ilP9O6jdW3Kfw8SvAjlfGdcNS3gmXs2sZsbxF7ldcofjbyMU5dUrcSuhGkvrjONMSm+Agy51KDrWozLBepMKOscXHO6bTNPilxhI2qYsg1I6Q0dwfHU0o4Av2U82q2fShi06ncx/vUTZvgtFdVEr13AGrM2lAhoA=
