sudo: required

services:
  - docker

env:
  global:
    - VERSION=latest
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=svn2git-mirror
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=svn2git-mirror
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/svn2git-mirror/KkTg5nSGpEj8NmQBMmAVJ3QSzko=
    - secure: DGOayQVTsgX8mO2vT0SdMp53uNJJ/znyVx90LmJZDRTxdWOZCsQfUTrkuM+gsBO4RV23ThPloc2kIC+s+NW+Z4vfZVK6XE2ZLRrelhbrz8AzUiV8Psh3Mc6vHKixl3FAYwTnQPxt7LcjAu+6z0+Hg073GEHFK1Mb8jtcgn40Bw6x2jnRnwrthwVauCIX9F1oCVahxyMC7lfifj0jxmnzQk8JBTYdTkvov7ok4GY9dAtx8RUKeWo5EBwvfThZZMPmxLfbz1VxySqGN2qnBXfKMphWtKeBRCBX4lcHMks9iFEQcQxriswV+rJg/f7mN17s5zxqbbVs96JKi5aHZa21hmWr9B5yODpTyJY6LNRxUDpXRAaS7OnLC79pPctIc8X5tMxUBnfqJkl+avrGe7AP/btJdAQswkqoX7NL+UzyAijvQ9do4MPUffEi7bB9vjHAyfhORmXn6z4jVKBUM+CLRNTou4S5uh9aTCMn4DjxXQx6NYQzaCxC1UqTvWmezi+udOnZ8hmlRGhcYl7Iv76o/glM+aXLSxJuWryrprLU/IeAlAufcP5cBdFxHqtmrWMAMsraamuVXUFtszCfsSVJ+zikICLt/+6Xlx+ISTEC6LyJMKv0UnDKZkcVk2d8WJ1u4Pklo+XQ/eZOV7eWEeCPYW/nvcy7qdQTuv/WEzDcaho= # DOCKER_PASSWORD
    - secure: kE5t+ogWBQ2Iiw7ZTRnamCgWrYa1gaDmdYAM75Fi75MdlFeUoWGuDYN1YirAsLwUFtl3B4Cjzq526YyG6sUyPXuI/6mWbRrUc0JsmEbEtQL6ESKywUXRfv7v+KiiH8msFpdsedzUHnZy0dulVw7ajFG6xO6YLzWksJJryQZ46FznqFuFO6mQUi3+hNn5LzDlfscEiOYpJv7lh7Szw2ylMy25AUfkaIpNA94cThSKh5CHmxco74RxwoTNmFPcrPKea+AqTuUUC+UeYKazVu6Ctheays9CBS4s2uPTr4WKmFeBeLxn23K9O6gYGt4xaQBboJlsvDn1Vt15+dW1PwvxL7FCE6sVp3g7M73MAtpbIruSoP2Dw6xCAT6ZI30nHfgjIQ3UHnMOTMPNGnCPm3hEFJKH7nZfTX2S0IGxx0RA+93t2+lMrLtmkZubnJkiLnV6zZg/A0SfSZuYKy3jXVz3bp/4d6s0fR1Beveafc6XBFAgfIjNoAgsAG99sMo2mrj/WZQbdUUek4+bulMqVCzI8CWFjsL93DH+Ij9antNu2v9sHEUxgGwb31l5Lr7W4OGBXEiiSfzieQjVh0c5s9W+qy473+fN96wnGNjV6QaN0oFqbwgVY4j4ry91P3Ymr+bbolnUABpLQsfGikmhUi2kqlTP0vIbNXg6gBjpPUPWmO0= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
